# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://ztred.github.io
date_format: "ordinal"
title: 幻想乡
subtitle: "接招吧!承太郎!阴险狡诈的白蛇换碟!!!"
description: "赵天瑞的幻象乡"
keywords: Zhao Tianrui, 幻想乡, Ztred , 赵天瑞
时区：中国/北京
编码：“ utf-8”
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Zhao Tianrui
organization: 
organization_url: 
github_username: ztred
location: Beijing, China
email: SiriusZhao@outlook.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: ztred/ztred.github.io

theme: jekyll-theme-minimal

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: ztred
    repo: blog-comments
    oauth:
        client_id: 135b279ffd2b298c755b
        client_secret: 4b78df0a412436b552cbe7daae508185958d9ec7
# https://github.com/gitalk/gitalk#install
gitalk:
    owner:ztred
    repo: blog-comments
    clientID: 135b279ffd2b298c755b
    clientSecret: 4b78df0a412436b552cbe7daae508185958d9ec7
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: true
    # 最多显示多少条搜索结果
    limit: 1000


