# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://ztred.github.io
date_format: "ordinal"
title: 幻想乡
subtitle: "接招吧!承太郎!阴险狡诈的白蛇换碟!!!"
description: "赵天瑞的幻象乡"
keywords: Zhao Tianrui, 幻想乡, Ztred , 赵天瑞
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Zhao Tianrui
organization: 
organization_url: 
github_username: ztred
location: Beijing, China
email: SiriusZhao@outlook.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: ztred/ztred.github.io

theme: jekyll-theme-minimal